# This is an example of a custom config file that will be deployed at build time.
#
# There are other parts to this example.
#   config/custom-settings.pre-clean: The build environment clean up part of 
#     the process.
#   config/custom-settings.pre-build: The pre-build deployment of the config 
#     file.
#   config/include.chroot_before_packages/example-custom-config.sh: A script 
#     that consumes the config.
#   config/hooks/normal/5052-example-custom-config.hook.chroot: The hook to 
#     run a program that consumes the config during the installed OS install 
#     process.  # FIXME: Verify this happens for the installed OS
#   config/hooks/live/0091-example-custom-config.hook.chroot: The hook to run 
#     a program that consumes the config during the live OS build process.
#   custom-settings/example-custom-config.conf: The config file to use during 
#     the build process or to include in the live OS and/or the installed OS. 
#     (this file)
#
# The purpose of doing this is that users doing custom builds can easily access
#    settings for things that happen during the build process. Hopefully that 
#    reduces the complexity of the build process for people who don't really 
#    need to understand it.
USER_LOCATION=AA00aa
