#!/bin/bash

# This is a common framework for hook scripts.
#
# To use it in a bash hook script do the following:
# 1. Create a `run_hook` function that is the entry point to the hook and may consume arguments. The arguments it will get depend on the type of hook.
# 2. Add the line `source "$(dirname "$0")"` somewhere after run_hook is defined.
#
# Required Environment Variables
#    BUILD_SH_REPO_DIR: The root of the build repository. Set in `build.sh`.

set -e -o pipefail

[[ -n "$BUILD_SH_REPO_DIR" ]] || (echo ERROR: BUILD_SH_REPO_DIR variable unset; exit 1)
pushd "$BUILD_SH_REPO_DIR" >/dev/null

# Load the shared config
# shellcheck disable=SC1091
source .build.sh.conf

# onfail/onsuccess scripts get the arguments given to the `onfail`/`onsuccess` functions.
run_hook "$@"

popd >/dev/null  # Return the previous working directory
