#!/bin/bash
#
# Required Environment Variables
#    BUILD_SH_REPO_DIR: The root of the build repository. Set in `build.sh`.

set -e -o pipefail

[[ -n "$BUILD_SH_REPO_DIR" ]] || (echo ERROR: BUILD_SH_REPO_DIR variable unset; exit 1)
pushd "$BUILD_SH_REPO_DIR" >/dev/null

# Load the shared config
source .build.sh.conf

# onfail/onsuccess scripts get the arguments given to the `onfail`/`onsuccess` functions.
run_hook "$@"

popd >/dev/null  # Return the previous working directory
