---

commands:
  - 'touch /calamares-post-install-string-command-ran-in-this-root.flag'
  - [touch, /calamares-post-install-list-command-ran-in-this-root.flag]
  - command: |
      touch /calamares-post-install-object-command-ran-in-this-root.flag
    in_target: false
